---
include:
  - board: nice_nano
    shield: corne_left nice_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: corne_right nice_oled
  
  - board: nice_nano
    shield: settings_reset
