# Temporary off nice_oled until it's fixed
---
include:
  - board: nice_nano
    # shield: corne_left nice_oled
    shield: corne_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    # shield: corne_right nice_oled
    shield: corne_right

  - board: nice_nano
    shield: settings_reset
